create table service (
    rid varchar(30) UNIQUE NOT NULL,
    uid varchar(10) UNIQUE NOT NULL,
    PRIMARY KEY(rid)
);
create table service_update (
    update_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIMESTAMP NOT NULL,
    rid varchar(30) NOT NULL,
    CONSTRAINT service_rid
        FOREIGN KEY(rid) 
        REFERENCES service(rid)
);
create table timestamp (
    ts_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts TIME NOT NULL,
    src varchar(30),
    delayed BOOLEAN,
    status varchar(30)
);
create table platform (
    plat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    src varchar(30),
    confirmed BOOLEAN,
    text varchar(30)
);
create table location (
    loc_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    update_id BIGINT,
    tpl varchar(10) NOT NULL,
    departure_id BIGINT UNIQUE,
    arrival_id BIGINT UNIQUE,
    platform_id BIGINT UNIQUE,
    CONSTRAINT service_update
        FOREIGN KEY(update_id) 
        REFERENCES service_update(update_id),
    CONSTRAINT departure_ts
        FOREIGN KEY(departure_id) 
        REFERENCES timestamp(ts_id),
    CONSTRAINT arrival_ts
        FOREIGN KEY(arrival_id) 
        REFERENCES timestamp(ts_id),
    CONSTRAINT platform_id
        FOREIGN KEY(platform_id) 
        REFERENCES platform(plat_id)
);